<?php
// app/Services/FlashcardService.php

namespace App\Services;

use App\Models\Flashcard;
use App\Models\FlashcardSet;
use App\Models\Course;
use App\Models\CourseOutline;
use App\Services\Ai\BaseAiService;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\DB;

class FlashcardService
{
    protected $aiService;

    public function __construct()
    {
        $this->aiService = BaseAiService::getDefaultService('deepseek');
    }

    /**
     * Create a new flashcard set
     */
    public function createFlashcardSet($userId, $courseId, $title, $description = null, $isPublic = false): FlashcardSet
    {
        return FlashcardSet::create([
            'user_id' => $userId,
            'course_id' => $courseId,
            'title' => $title,
            'description' => $description,
            'is_public' => $isPublic,
            'study_mode' => 'spaced_repetition',
        ]);
    }

    /**
     * Generate flashcards using AI
     */
    public function generateFlashcards(FlashcardSet $flashcardSet, $course, $outline = null, $numberOfCards = 10, $difficultyLevel = 'medium', $includeExplanations = false): array
    {
        $prompt = $this->buildFlashcardPrompt($course, $outline, $numberOfCards, $difficultyLevel, $includeExplanations);

        try {
            $response = $this->aiService->chat([
                ['role' => 'system', 'content' => 'You are an expert educational content creator. Generate high-quality flashcards in JSON format.'],
                ['role' => 'user', 'content' => $prompt]
            ], [
                'temperature' => 0.7,
                'max_tokens' => 2000,
            ], 'flashcards');

            $flashcards = json_decode($response, true);

            if (!is_array($flashcards) || empty($flashcards)) {
                throw new \Exception('Invalid flashcard format generated by AI');
            }

            $createdFlashcards = [];
            foreach (array_slice($flashcards, 0, $numberOfCards) as $flashcardData) {
                $createdFlashcards[] = $this->createFlashcard(
                    $flashcardSet, // Pass the flashcard set
                    $flashcardData['question'] ?? '',
                    $flashcardData['answer'] ?? '',
                    $flashcardData['explanation'] ?? null,
                    $difficultyLevel,
                    $outline?->id // Pass the outline ID
                );
            }

            return $createdFlashcards;

        } catch (\Exception $e) {
            Log::error('AI flashcard generation failed', [
                'flashcard_set_id' => $flashcardSet->id,
                'course_id' => $course->id,
                'outline_id' => $outline?->id,
                'error' => $e->getMessage()
            ]);

            // Fallback to manual flashcard generation
            return $this->generateFallbackFlashcards($flashcardSet, $course, $outline, $numberOfCards, $difficultyLevel);
        }
    }

    /**
     * Create a single flashcard
     */
    public function createFlashcard(FlashcardSet $flashcardSet, $question, $answer, $explanation = null, $difficultyLevel = 'medium', $courseOutlineId = null): Flashcard
    {
        return Flashcard::create([
            'user_id' => $flashcardSet->user_id,
            'course_id' => $flashcardSet->course_id,
            'course_outline_id' => $courseOutlineId,
            'flashcard_set_id' => $flashcardSet->id,
            'question' => $question,
            'answer' => $answer,
            'explanation' => $explanation,
            'difficulty_level' => $difficultyLevel,
            'is_public' => false,
            'ease_factor' => 2.5,
            'repetitions' => 0,
            'interval' => 0,
            'next_review_date' => now(),
        ]);
    }

    /**
     * Update flashcard progress using spaced repetition (SM-2 algorithm)
     */
    public function updateFlashcardProgress(Flashcard $flashcard, int $quality): Flashcard
    {
        // SM-2 algorithm implementation
        if ($quality >= 3) {
            if ($flashcard->repetitions == 0) {
                $flashcard->interval = 1;
            } elseif ($flashcard->repetitions == 1) {
                $flashcard->interval = 6;
            } else {
                $flashcard->interval = round($flashcard->interval * $flashcard->ease_factor);
            }

            $flashcard->repetitions++;
        } else {
            $flashcard->repetitions = 0;
            $flashcard->interval = 1;
        }

        // Update ease factor (minimum 1.3)
        $flashcard->ease_factor = max(1.3, $flashcard->ease_factor + (0.1 - (5 - $quality) * (0.08 + (5 - $quality) * 0.02)));

        // Set next review date
        $flashcard->next_review_date = now()->addDays($flashcard->interval);
        $flashcard->last_studied_at = now();
        $flashcard->study_interval = $flashcard->interval;

        $flashcard->save();

        return $flashcard;
    }

    /**
     * Get flashcards due for review
     */
    public function getDueFlashcards($userId, $flashcardSetId = null): array
    {
        $query = Flashcard::where('user_id', $userId)
            ->where(function($query) {
                $query->where('next_review_date', '<=', now())
                      ->orWhereNull('next_review_date');
            });

        if ($flashcardSetId) {
            $query->where('flashcard_set_id', $flashcardSetId);
        }

        return [
            'due_count' => $query->count(),
            'flashcards' => $query->orderBy('next_review_date')->get()
        ];
    }

    /**
     * Get study statistics for a user
     */
    public function getStudyStatistics($userId): array
    {
        $totalFlashcards = Flashcard::where('user_id', $userId)->count();
        $dueFlashcards = Flashcard::where('user_id', $userId)
            ->where(function($query) {
                $query->where('next_review_date', '<=', now())
                      ->orWhereNull('next_review_date');
            })
            ->count();

        $recentlyStudied = Flashcard::where('user_id', $userId)
            ->where('last_studied_at', '>=', now()->subDays(7))
            ->count();

        $masteredFlashcards = Flashcard::where('user_id', $userId)
            ->where('repetitions', '>=', 5)
            ->where('ease_factor', '>=', 2.0)
            ->count();

        return [
            'total_flashcards' => $totalFlashcards,
            'due_flashcards' => $dueFlashcards,
            'recently_studied' => $recentlyStudied,
            'mastered_flashcards' => $masteredFlashcards,
            'mastery_percentage' => $totalFlashcards > 0 ? round(($masteredFlashcards / $totalFlashcards) * 100, 2) : 0,
        ];
    }

    /**
     * Build AI prompt for flashcard generation
     */
    protected function buildFlashcardPrompt($course, $outline, $numberOfCards, $difficultyLevel, $includeExplanations): string
    {
        $prompt = "Generate exactly {$numberOfCards} educational flashcards for a {$difficultyLevel} difficulty level.";

        if ($outline) {
            $prompt .= "\n\nTOPIC: {$outline->title}";
            $prompt .= "\nDESCRIPTION: {$outline->description}";

            if ($outline->learning_objectives && is_array($outline->learning_objectives)) {
                $prompt .= "\nLEARNING OBJECTIVES: " . implode(', ', $outline->learning_objectives);
            }

            if ($outline->key_concepts && is_array($outline->key_concepts)) {
                $prompt .= "\nKEY CONCEPTS: " . implode(', ', $outline->key_concepts);
            }
        } else {
            $prompt .= "\n\nCOURSE: {$course->title}";
            $prompt .= "\nSUBJECT: {$course->subject}";
            $prompt .= "\nLEVEL: {$course->level}";

            if ($course->learning_objectives && is_array($course->learning_objectives)) {
                $prompt .= "\nCOURSE LEARNING OBJECTIVES: " . implode(', ', $course->learning_objectives);
            }
        }

        $prompt .= "\n\nPlease generate flashcards with:";
        $prompt .= "\n- Clear, concise questions";
        $prompt .= "\n- Accurate, educational answers";
        $prompt .= "\n- Appropriate difficulty level for {$difficultyLevel}";

        if ($includeExplanations) {
            $prompt .= "\n- Helpful explanations for better understanding";
        }

        $prompt .= "\n\nFLASHCARD GUIDELINES:";
        $prompt .= "\n- Questions should test understanding, not just recall";
        $prompt .= "\n- Answers should be comprehensive but concise";
        $prompt .= "\n- Focus on key concepts and important details";
        $prompt .= "\n- Avoid trivial or overly specific information";
        $prompt .= "\n- Ensure questions and answers are educationally valuable";

        $prompt .= "\n\nReturn ONLY a valid JSON array with this exact structure:";
        $prompt .= "\n[";
        $prompt .= "\n  {";
        $prompt .= "\n    \"question\": \"Clear question here?\",";
        $prompt .= "\n    \"answer\": \"Comprehensive answer here.\",";
        if ($includeExplanations) {
            $prompt .= "\n    \"explanation\": \"Additional context or explanation here.\",";
        }
        $prompt .= "\n  }";
        $prompt .= "\n]";
        $prompt .= "\n\nDo not include any other text, only the JSON array.";

        return $prompt;
    }

    /**
     * Fallback flashcard generation when AI fails
     */
    protected function generateFallbackFlashcards(FlashcardSet $flashcardSet, $course, $outline, $numberOfCards, $difficultyLevel): array
    {
        $baseContent = $outline ? $outline->title : $course->title;
        $createdFlashcards = [];

        for ($i = 1; $i <= $numberOfCards; $i++) {
            $createdFlashcards[] = $this->createFlashcard(
                $flashcardSet,
                "What is key concept {$i} in {$baseContent}?",
                "This is the explanation for key concept {$i} in {$baseContent}. " .
                "It represents an important aspect of the subject matter that students should understand.",
                "This concept is important because it forms the foundation for more advanced topics " .
                "and helps build a comprehensive understanding of {$baseContent}.",
                $difficultyLevel,
                $outline?->id
            );
        }

        Log::info('Used fallback flashcard generation', [
            'flashcard_set_id' => $flashcardSet->id,
            'number_of_cards' => $numberOfCards
        ]);

        return $createdFlashcards;
    }

    /**
     * Duplicate a flashcard set for another user
     */
    public function duplicateFlashcardSet(FlashcardSet $originalSet, $newUserId): FlashcardSet
    {
        return DB::transaction(function () use ($originalSet, $newUserId) {
            // Create new flashcard set
            $newSet = $this->createFlashcardSet(
                $newUserId,
                $originalSet->course_id,
                $originalSet->title . ' (Copy)',
                $originalSet->description,
                false
            );

            // Duplicate all flashcards
            foreach ($originalSet->flashcards as $originalFlashcard) {
                $this->createFlashcard(
                    $newSet,
                    $originalFlashcard->question,
                    $originalFlashcard->answer,
                    $originalFlashcard->explanation,
                    $originalFlashcard->difficulty_level,
                    $originalFlashcard->course_outline_id
                );
            }

            return $newSet;
        });
    }

    /**
     * Search flashcards by keyword
     */
    public function searchFlashcards($userId, $searchTerm, $courseId = null): array
    {
        $query = Flashcard::where('user_id', $userId)
            ->where(function($query) use ($searchTerm) {
                $query->where('question', 'like', "%{$searchTerm}%")
                      ->orWhere('answer', 'like', "%{$searchTerm}%")
                      ->orWhere('explanation', 'like', "%{$searchTerm}%");
            });

        if ($courseId) {
            $query->where('course_id', $courseId);
        }

        return [
            'results' => $query->with('flashcardSet', 'course')->get(),
            'total_count' => $query->count()
        ];
    }

    /**
     * Get recommended study sessions based on due cards
     */
    public function getRecommendedStudySessions($userId): array
    {
        $dueCards = $this->getDueFlashcards($userId);
        $totalDue = $dueCards['due_count'];

        $sessions = [];

        if ($totalDue > 0) {
            $sessions[] = [
                'type' => 'due_cards',
                'title' => 'Review Due Cards',
                'description' => "You have {$totalDue} cards due for review",
                'priority' => 'high',
                'estimated_time' => ceil($totalDue * 1.5), // 1.5 minutes per card
                'due_cards' => $totalDue
            ];
        }

        // Add session for new cards if user has been active
        $recentActivity = Flashcard::where('user_id', $userId)
            ->where('last_studied_at', '>=', now()->subDays(3))
            ->exists();

        if ($recentActivity && $totalDue < 10) {
            $sessions[] = [
                'type' => 'new_cards',
                'title' => 'Learn New Cards',
                'description' => 'Add and study new flashcards',
                'priority' => 'medium',
                'estimated_time' => 20,
                'due_cards' => 0
            ];
        }

        return $sessions;
    }

    /**
     * Reset flashcard progress for a set
     */
    public function resetFlashcardProgress(FlashcardSet $flashcardSet): void
    {
        Flashcard::where('flashcard_set_id', $flashcardSet->id)
            ->update([
                'repetitions' => 0,
                'interval' => 0,
                'ease_factor' => 2.5,
                'next_review_date' => now(),
                'last_studied_at' => null,
                'study_interval' => 0,
            ]);

        Log::info('Flashcard progress reset', [
            'flashcard_set_id' => $flashcardSet->id,
            'user_id' => $flashcardSet->user_id
        ]);
    }

    /**
     * Get AI service instance (for testing or external use)
     */
    public function getAiService(): BaseAiService
    {
        return $this->aiService;
    }
}
